### ISSUE TITLE
add code editor to hud

### ISSUE THREAD

**Issue by cjpappas** [cjpappas/MacSim#16]
Add a code editor to the hud which takes up the right half of the screen, allowing people to write code to control the boat.

**Comment by altmattr** [comment]
would be good if we could trigger its presence with a url parameter

`https://whatever.com/hud?ide=true`

**Comment by cjpappas** [comment]
Pending review in https://github.com/cjpappas/MacSim/pull/28.

**Comment by cjpappas** [comment]
Closed in pull pull request #28
