### ISSUE TITLE
add demo programs

### ISSUE THREAD

**Issue by cjpappas** [cjpappas/MacSim#17]
Few ideas:
- simple example of utilising a loop to write continuous code
- naive implementation of station keeping

**Comment by altmattr** [comment]
and create URLS that encode them! 

`https://whatever/com/hud?ide=true&code=90jipnu9ph89phb8upbd8ph89`

 Make a "landing page" with links to the different demos

**Comment by altmattr** [comment]
I'm thinking about what the code will look like with the current api.  I am keen to get a "processing" version going with `setup` and `act`.  I think acting every second would be OK and will fit with the existing simulation setup (that you found!).  The HUD can even show a thinking icon whenever the boat is running the act function.

I am fairly sure the api could detect the presence of `setup` and `act` functions and run them for us - a kind of "active mode".  I am going to need another issue for this.  For now!

**Comment by cjpappas** [comment]
So it looks like:
1. Create landing page
2. Do the active mode stuff reference in #20 
3. Add url encoded demo programs

**Comment by cjpappas** [comment]
Only thing left to do is add a decent example of station keeping.

**Comment by cjpappas** [comment]
DONE
