### ISSUE TITLE
thrust commands only have an effect for a certain amount of time

### ISSUE THREAD

**Issue by altmattr** [cjpappas/MacSim#7]
how long is this time?  We need to know so that we know how often we have to send the command to make it "continuous"

**Comment by cjpappas** [comment]
Looks like the default is 1 second according to the [docs](https://github.com/osrf/vrx/wiki/driving_programmatic_tutorial#rostopic-pub). This can be changed by editing the wamv_gazebo_thruster_config.xacro file. I think for all purposes from here out we just assume it runs for 1s and plan accordingly.
